// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WildNatureExplorer.Infrastructure.Data;

#nullable disable

namespace WildNatureExplorer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428_AddIndexesAndAuditTrail")]
    partial class AddIndexesAndAuditTrail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Base configuration remains from previous migrations
            // This is auto-generated and updated by EF Core

#pragma warning restore 612, 618
        }
    }
}
