export const termsText = `
Privacy Policy (WildNatureExplorer)
1. General Information

This application and/or website (hereinafter referred to as the “Service”) is created solely for entertainment purposes. The Service is not intended to provide professional advice, including but not limited to medical, legal, financial, or other specialized consultations.

2. Nature of Information

All responses generated by the integrated artificial intelligence (AI assistant) are provided strictly for informational and entertainment purposes only. They do not constitute professional advice, guidance, or official statements from the Service owners or developers.

The user acknowledges and agrees that:

information provided by the AI assistant may be inaccurate, incomplete, or outdated;
before making any decisions based on such information, the user is strongly advised to independently verify the information using reliable sources or consult qualified professionals.
3. Limitation of Liability

The developers, owners, and administrators of the Service shall not be held liable for any direct or indirect damages, losses, or consequences arising from the use of or inability to use the Service, including actions taken by the user based on information provided by the AI assistant.

4. Waiver of Claims

By using the Service, the user confirms that they do so voluntarily and with full awareness of the limitations of the information provided.

To the maximum extent permitted by applicable law, the user agrees to waive any claims, demands, or legal actions against the owners, developers, and affiliated parties of the Service arising from the use or interpretation of information obtained through the Service.

5. Acceptance of Terms

By accessing or using the Service, the user acknowledges and agrees to be bound by these terms.

Version: 1.0
`;